language: swift
osx_image: xcode9.2
xcode_project: 2F.xcodeproj # path to your xcodeproj folder
xcode_scheme: 2FTests
install: pod install --repo-update
after_success:
  - bash <(curl -s https://codecov.io/bash)
